name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push"]  # <-- Must match the `name:` in build.yml
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull shubhamkushwah123/war-test-app:${{ github.sha }}
          docker stop war-test || true
          docker rm war-test || true
          docker run -d --name war-test -p 8080:8080 --restart unless-stopped shubhamkushwah123/war-test-app:${{ github.sha }}
